"""
Module with various built-in functions known to a database

List of built-in functions found in a in-memory database;
                      POW:
             GROUP_CONCAT:
                JULIANDAY:
                    NTILE:
                   NULLIF:
 SQLITE_COMPILEOPTION_GET:
        CURRENT_TIMESTAMP:
                    POWER:
SQLITE_COMPILEOPTION_USED:
                      SIN:
                      SUM:
                    QUOTE:
                   PRINTF:
               LIKELIHOOD:
               LAST_VALUE:
                     RANK:
                     SIGN:
                     SQRT:
                     SINH:
                      TAN:
                    ROUND:
                    RTRIM:
                NTH_VALUE:
                     TANH:
                   RANDOM:
                     TRIM:
                     TIME:
                  RADIANS:
                    TRUNC:
                    TOTAL:
                   SUBSTR:
                  REPLACE:
                    UPPER:
                   TYPEOF:
           LOAD_EXTENSION:
                      AVG:
                      ABS:
                 STRFTIME:
                     ATAN:
                     ASIN:
                     ACOS:
                SUBSTRING:
               RANDOMBLOB:
                  UNICODE:
             PERCENT_RANK:
               ROW_NUMBER:
                    ATANH:
                    ASINH:
                    ACOSH:
                      COS:
                    ATAN2:
        LAST_INSERT_ROWID:
               SQLITE_LOG:
                 UNLIKELY:
                     COSH:
                     CEIL:
                     CHAR:
                      EXP:
                    COUNT:
                     DATE:
                  CEILING:
            TOTAL_CHANGES:
                  CHANGES:
           SQLITE_VERSION:
                  DEGREES:
                    FLOOR:
                 COALESCE:
                     GLOB:
                 ZEROBLOB:
                      HEX:
                      IIF:
         SQLITE_SOURCE_ID:
                 DATETIME:
                CUME_DIST:
                       LN:
                    INSTR:
               DENSE_RANK:
                      LOG:
                   IFNULL:
             CURRENT_DATE:
             CURRENT_TIME:
                      LAG:
                      MOD:
                     LOG2:
                     LIKE:
                      MAX:
                      MIN:
                     LEAD:
                    LOG10:
                    LOWER:
                    LTRIM:
              FIRST_VALUE:
                       PI:
                   LENGTH:
                   LIKELY:
             JSON_REPLACE:
                JSON_TYPE:
              JSON_REMOVE:
               JSON_QUOTE:
        JSON_GROUP_OBJECT:
             JSON_EXTRACT:
         JSON_GROUP_ARRAY:
               JSON_ARRAY:
                     JSON:
               RTREEDEPTH:
                 JSON_SET:
               JSON_PATCH:
                    MATCH:
                  SNIPPET:
           FTS5_SOURCE_ID:
                  OFFSETS:
               JSON_VALID:
                MATCHINFO:
        JSON_ARRAY_LENGTH:
                 OPTIMIZE:
              JSON_OBJECT:
               RTREECHECK:
                RTREENODE:
                HIGHLIGHT:
                     BM25:
              JSON_INSERT:
           FTS3_TOKENIZER:
                     FTS5:
"""